services:
  - type: cron
    name: amazon-affiliate-bot
    env: python
    schedule: "0 2 * * *"  # Runs daily at 8:00 AM IST (2:00 AM UTC)
    buildCommand: "./start.sh"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
