services:
  - type: cron
    name: amazon-affiliate-bot
    runtime: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: |
      playwright install
      python main.py
    schedule: '0 2 * * *'  # IST 8:00 AM = UTC 2:00 AM
